account_id = "59a19a8616a9fa02c1b926eca21347c2"
name = "inkrss"
type = "webpack"
workers_dev = true

# These fields specify that the Worker(s) will deploy to a custom domain
# route = ""
# zone_id = ""

target_type = "webpack"
webpack_config = "webpack.config.js"

kv_namespaces = [
     { binding = "inkrss", id = "417fb3b6021040bd8c4b0c7376d0ff58", preview_id = "" }
]

[triggers]
crons = ["*/1 * * * *"]

[site]
bucket = "./public"
entry-point = "./"

# Global variables can be used by the Worker scripts.
# NOT inherited. Need to define in each environment.
[vars]
NOTIFIER = "bark" # bark, telegram or wechat
PARSE_URL = "https://rssparse.vercel.app"
SECRET_PATH = "rss" 

# Bark notification
BARK_URL = "http://10.168.38.7:8800"

# Telegram notification
TELEGRAPH_TOKEN = ""
TG_TOKEN = ""

TG_SENDID = 123456789 # OR "@channel_name"
TG_USERID = 123456789 

# WeChat notification
WECHAT_URL = ""

# # Environments / Multiple Workers
# # Ref: https://developers.cloudflare.com/workers/platform/environments

# [env.production]
# name = "inkrss"
# # workers_dev = false
# # route = ""
# # zone_id = ""
# kv_namespaces = [
#   #   { binding = "KV", id = "" }
# ]

# [env.production.vars]
# NOTIFIER = "telegram" # bark, telegram or wechat

# PARSE_URL = ""
# SECRET_PATH = ""

# # Telegram notification
# TELEGRAPH_TOKEN = ""
# TG_TOKEN = ""

# TG_SENDID = 123456789 # OR "@channel_name"
# TG_USERID = 123456789
