name: Deploy

on:
  push:
    branches:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.cloudflare_API_TOKEN }}
          wranglerVersion: '1.13.0'
